version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      # These are not directly used by CodeIgniter's database.php,
      # but can be useful for other configurations or if database.php
      # is modified to use environment variables.
      # For now, the database.php file will be modified to use 'db' as hostname.
      DB_HOSTNAME: db
      DB_USERNAME: 
      DB_PASSWORD: 
      DB_DATABASE: 
    depends_on:
      - db

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD:  # Change this to a strong password
      MYSQL_DATABASE: 
      MYSQL_USER: 
      MYSQL_PASSWORD: 
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
